version: '3'
services:
    node-swagger-template:
        build: .
        container_name: "live-talk-server"
        environment:
            - NODE_ENV=development
        ports:
            - 80:10010
        links:
            - mongo
    mongo:
        image: mongo:latest
        container_name: "mongo"
        ports:
            - 27017:27017